// <auto-generated />
using System;
using FoodDelivery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodDelivery.Migrations
{
    [DbContext(typeof(FoodDeliveryDbContext))]
    partial class FoodDeliveryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("FoodDelivery.Models.FavoritoRestaurante", b =>
                {
                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteId", "RestauranteId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("FavoritosRestaurantes");
                });

            modelBuilder.Entity("FoodDelivery.Models.ItemPedido", b =>
                {
                    b.Property<Guid>("PedidoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("PedidoId", "ProdutoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("FoodDelivery.Models.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPedidoUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MotoboyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MotoboyId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("FoodDelivery.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoProduto")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("Produtos");

                    b.HasDiscriminator<int>("TipoProduto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FoodDelivery.Models.Restaurante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("FoodDelivery.Models.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("AppUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FoodDelivery.Models.Bebida", b =>
                {
                    b.HasBaseType("FoodDelivery.Models.Produto");

                    b.Property<bool>("Alcoolica")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolumeMl")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("FoodDelivery.Models.Prato", b =>
                {
                    b.HasBaseType("FoodDelivery.Models.Produto");

                    b.Property<string>("ObservacoesPreparo")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("TempoPreparoMin")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("FoodDelivery.Models.Users.Administrador", b =>
                {
                    b.HasBaseType("FoodDelivery.Models.Users.AppUser");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("FoodDelivery.Models.Users.Cliente", b =>
                {
                    b.HasBaseType("FoodDelivery.Models.Users.AppUser");

                    b.Property<string>("Endereco")
                        .HasMaxLength(220)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("FoodDelivery.Models.Users.Motoboy", b =>
                {
                    b.HasBaseType("FoodDelivery.Models.Users.AppUser");

                    b.Property<string>("PlacaVeiculo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Motoboy");
                });

            modelBuilder.Entity("FoodDelivery.Models.Users.RestauranteUser", b =>
                {
                    b.HasBaseType("FoodDelivery.Models.Users.AppUser");

                    b.Property<string>("Cargo")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RestauranteId")
                        .HasColumnType("TEXT");

                    b.HasIndex("RestauranteId");

                    b.HasDiscriminator().HasValue("RestauranteUser");
                });

            modelBuilder.Entity("FoodDelivery.Models.FavoritoRestaurante", b =>
                {
                    b.HasOne("FoodDelivery.Models.Users.Cliente", "Cliente")
                        .WithMany("Favoritos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDelivery.Models.Restaurante", "Restaurante")
                        .WithMany("Favoritos")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("FoodDelivery.Models.ItemPedido", b =>
                {
                    b.HasOne("FoodDelivery.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDelivery.Models.Produto", "Produto")
                        .WithMany("ItensPedido")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("FoodDelivery.Models.Pedido", b =>
                {
                    b.HasOne("FoodDelivery.Models.Users.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodDelivery.Models.Users.Motoboy", "Motoboy")
                        .WithMany("Entregas")
                        .HasForeignKey("MotoboyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FoodDelivery.Models.Restaurante", "Restaurante")
                        .WithMany("Pedidos")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Motoboy");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("FoodDelivery.Models.Produto", b =>
                {
                    b.HasOne("FoodDelivery.Models.Restaurante", "Restaurante")
                        .WithMany("Produtos")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("FoodDelivery.Models.Users.RestauranteUser", b =>
                {
                    b.HasOne("FoodDelivery.Models.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("FoodDelivery.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("FoodDelivery.Models.Produto", b =>
                {
                    b.Navigation("ItensPedido");
                });

            modelBuilder.Entity("FoodDelivery.Models.Restaurante", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("Pedidos");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("FoodDelivery.Models.Users.Cliente", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("FoodDelivery.Models.Users.Motoboy", b =>
                {
                    b.Navigation("Entregas");
                });
#pragma warning restore 612, 618
        }
    }
}
